package Vista;
<<<<<<< HEAD

=======
>>>>>>> fcee56b (Actualizado)
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
<<<<<<< HEAD
=======
import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
>>>>>>> fcee56b (Actualizado)

/**
 *
 * @author angel
 */
public class Informes extends javax.swing.JFrame {
<<<<<<< HEAD
=======
    

>>>>>>> fcee56b (Actualizado)

    /**
     * Creates new form Informes
     */
    public Informes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
=======
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnatrasinfo = new javax.swing.JButton();
        cortecaja = new javax.swing.JButton();
        reporteventas = new javax.swing.JButton();
        reporteproveedores = new javax.swing.JButton();
        devoluciones = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
>>>>>>> fcee56b (Actualizado)

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
<<<<<<< HEAD

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Corte de Caja - Hoy", "- - - - - - - - - - - - - - - - - - - - - - - - - - - - -", "Ingresos: Precios", "Gastos: Precios", "Saldo Final: Precios" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Devoluciones y Calcelaciones - Hoy", "- - - - - - - - - -- - - - - - - - - - - - - - - - - - - - -", "Numero Total de Devoluciones: 3", "Motivos de devolucion", "- Cliente recibio el producto equivocado (2 casos)", "- Producto danano (2 casos)", "Monto total reembolsado: precio" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Reporte de Proveedores", "- - - - - - - - - - - - - - - - - - - - - - - - - - - - -", "Proveedor: FarmaPlus(ejemplo)", "- Ultima entrega: 18 de febrero", "- Proximo pedido: 25 de febrero", "Proveedor: SalusExpress", "- Ultima entrega: 15 de febrero", "- Proximo pedido: 22 de febrero" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Reporte de Ventas - Hoy", "- - - - - - - - - -- - - - - - - - - - - - - - - - - - - - -", "Total de Productos Vendidos: cant unidades", "Producto mas vendido: Nom produc", "Hora de mayor venta: 1:00 - 2:00", "Clientes frecuentes:", "Metodos de pagos mas usados:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jButton2.setText("Guardar Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
=======
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
>>>>>>> fcee56b (Actualizado)

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informe de la farmacia");
        jLabel1.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Logo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addContainerGap(171, Short.MAX_VALUE))
>>>>>>> fcee56b (Actualizado)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

<<<<<<< HEAD
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jButton2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
=======
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 726, -1));

        btnatrasinfo.setText("Atras");
        btnatrasinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasinfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnatrasinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 101, -1, -1));

        cortecaja.setBackground(new java.awt.Color(204, 255, 255));
        cortecaja.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cortecaja.setText("Corte de Caja");
        cortecaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cortecajaActionPerformed(evt);
            }
        });
        getContentPane().add(cortecaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 270, -1));

        reporteventas.setBackground(new java.awt.Color(204, 255, 255));
        reporteventas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        reporteventas.setText("Reporte de ventas");
        reporteventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteventasActionPerformed(evt);
            }
        });
        getContentPane().add(reporteventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, -1));

        reporteproveedores.setBackground(new java.awt.Color(204, 255, 255));
        reporteproveedores.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        reporteproveedores.setText("Corte de Caja General");
        reporteproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteproveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(reporteproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 270, -1));

        devoluciones.setBackground(new java.awt.Color(204, 255, 255));
        devoluciones.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        devoluciones.setText("Devoluciones y Calcelaciones");
        devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucionesActionPerformed(evt);
            }
        });
        getContentPane().add(devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 270, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void btnatrasinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasinfoActionPerformed
        this.dispose();
        Interfaz1 R2 = new Interfaz1();
        R2.setVisible(true);
        R2.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnatrasinfoActionPerformed

    private void cortecajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cortecajaActionPerformed
    pdfcorte();
    n1++;
    
    
    }//GEN-LAST:event_cortecajaActionPerformed

    private void reporteventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteventasActionPerformed
pdf();       
n++;
int c=n;
    }//GEN-LAST:event_reporteventasActionPerformed

    private void reporteproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteproveedoresActionPerformed
pdfcortegeneral();
n2++;// TODO add your handling code here:
    }//GEN-LAST:event_reporteproveedoresActionPerformed

    private void devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucionesActionPerformed
pdfdevolucionescalcelaciones();
n3++;// TODO add your handling code here:
    }//GEN-LAST:event_devolucionesActionPerformed
>>>>>>> fcee56b (Actualizado)

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informes().setVisible(true);
            }
        });
    }

<<<<<<< HEAD
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
=======
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatrasinfo;
    private javax.swing.JButton cortecaja;
    private javax.swing.JButton devoluciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton reporteproveedores;
    private javax.swing.JButton reporteventas;
    // End of variables declaration//GEN-END:variables

      int n=0;
      int n1=0;
      int n2=0;
      int n3=0;
      int n4=0;
      
    private void pdf(){
        try {
            
          
            
            FileOutputStream archivo;
            File file = new File("src/pdf/Venta"+n+".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/imagenes/soporte.jpg");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.TIMES_ROMAN, 12, Font.BOLD,Color.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date = new Date();
            fecha.add("Factura: 1\n"+"Fecha: "+new SimpleDateFormat("DD-MM-YYYY".formatted(date)+"\n\n"));
            
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
             Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
             Encabezado.addCell(img);
             String roo = "212456545";
             String nom = "REPORTE DE VENTA";
             String tel = "7444203005";
             String dir = "Acapulco";
             String ra = "jija";
             
            Encabezado.addCell("");
            Encabezado.addCell("Ruc: "+roo+ "\nNombre: "+nom+"\nTelefono: "+tel+ "\n direccion: "+dir+"\nRazon: "+ra);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);
          
            
            doc.close();
            archivo.close();
            
            JOptionPane.showMessageDialog(this, "se genero el documento: ");
            
        }
                     catch (DocumentException | FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al generar el documento: "+ ex.getMessage());
                     }
          
        catch (Exception e) {
        }
    
    
}
    
private void pdfcorte(){
        try {
            
         
            
            FileOutputStream archivo;
            File file = new File("src/pdf/Corte"+n1+".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/imagenes/soporte.jpg");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.TIMES_ROMAN, 12, Font.BOLD,Color.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date= new Date();
            
            
            fecha.add("factura: 1\n"+"Fecha: "+new SimpleDateFormat("DD-MM-YYYY".formatted(date)+"\n\n"));
            
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
             Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
             Encabezado.addCell(img);
             String roo = "212456545";
             String nom = "FARMACIA POCHOCO";
             String tel = "7444203005";
             String dir = "Acapulco";
             String ra = "jija";
             String p = "s.v de SA";
                   
             
             Encabezado.addCell("");
             Encabezado.addCell("Ruc: "+roo+ "\nNombre: "+nom+"\nTelefono: "+tel+ "\n direccion: "+dir+"\nRazon: "+ra);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);
             
            
            
            doc.close();
            archivo.close();
            
            JOptionPane.showMessageDialog(this, "se genero el documento: ");
            
        }
                     catch (DocumentException | FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al generar el documento: "+ ex.getMessage());
                     }
          
        catch (Exception e) {
        }
}

private void pdfcortegeneral(){
        try {
            
         
            
            FileOutputStream archivo;
            File file = new File("src/pdf/cortegeneral"+n2+".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/imagenes/soporte.jpg");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.TIMES_ROMAN, 12, Font.BOLD,Color.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date= new Date();
            
            
            fecha.add("factura: 1\n"+"Fecha: "+new SimpleDateFormat("DD-MM-YYYY".formatted(date)+"\n\n"));
            
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
             Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
             Encabezado.addCell(img);
             String roo = "212456545";
             String nom = "CORTE GENERAL";
             String tel = "7444203005";
             String dir = "Acapulco";
             String ra = "jija";
             String p = "s.v de SA";
                   
             
             Encabezado.addCell("");
             Encabezado.addCell("Ruc: "+roo+ "\nNombre: "+nom+"\nTelefono: "+tel+ "\n direccion: "+dir+"\nRazon: "+ra);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);
             
            
            
            doc.close();
            archivo.close();
            
            JOptionPane.showMessageDialog(this, "se genero el documento: ");
            
        }
                     catch (DocumentException | FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al generar el documento: "+ ex.getMessage());
                     }
          
        catch (Exception e) {
        }
}


private void pdfdevolucionescalcelaciones(){
        try {
            
         
            
            FileOutputStream archivo;
            File file = new File("src/pdf/devolucionescalcelaciones"+n3+".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/imagenes/soporte.jpg");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.TIMES_ROMAN, 12, Font.BOLD,Color.BLUE);
            fecha.add(Chunk.NEWLINE);
            Date date= new Date();
            
            
            fecha.add("factura: 1\n"+"Fecha: "+new SimpleDateFormat("DD-MM-YYYY".formatted(date)+"\n\n"));
            
            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setWidths(ColumnaEncabezado);
             Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            
             Encabezado.addCell(img);
             String roo = "212456545";
             String nom = "DEVOLUCIONES Y CALCELACIONES";
             String tel = "7444203005";
             String dir = "Acapulco";
             String ra = "jija";
             String p = "s.v de SA";
                   
             
             Encabezado.addCell("");
             Encabezado.addCell("Ruc: "+roo+ "\nNombre: "+nom+"\nTelefono: "+tel+ "\n direccion: "+dir+"\nRazon: "+ra);
            Encabezado.addCell(fecha);
            doc.add(Encabezado);
             
            
            
            doc.close();
            archivo.close();
            
            JOptionPane.showMessageDialog(this, "se genero el documento: ");
            
        }
                     catch (DocumentException | FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al generar el documento: "+ ex.getMessage());
                     }
          
        catch (Exception e) {
        }
}

}


>>>>>>> fcee56b (Actualizado)
